spring:
  datasource:
    url: jdbc:mysql://localhost/zhijianju1?useSSL=true&autoReconnect=true&characterEncoding=UTF-8
    username: root
    password: WOAIwojia5069
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  main:
    banner-mode: off
  redis:
    host: localhost
    port: 6379
logging:
  file: out.log